import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from "next/font/local";
import NavBar from "./NavBar";
import AuthProvider from "./auth/provider";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({ subsets: ["latin"], weight: ["300", "500", "900"] });

const poppins = localFont({
    src: "../public/fonts/poppins-regular-webfont.woff2",
    variable: "--font-poppins",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    openGraph: {
        title: "Next.js",
        description: "The React Framework for the Web",
        url: "https://nextjs.org",
        siteName: "Next.js",
        images: [
            {
                url: "https://nextjs.org/og.png",
                width: 800,
                height: 600,
            },
            {
                url: "https://nextjs.org/og-alt.png",
                width: 1800,
                height: 1600,
                alt: "My custom alt",
            },
        ],
        locale: "en_US",
        type: "website",
    },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" data-theme="winter">
            <body className={poppins.variable}>
                <GoogleAnalyticsScript />
                <AuthProvider>
                    <NavBar />
                    <main className="m-5">{children}</main>
                </AuthProvider>
            </body>
        </html>
    );
}
